import type { Contest } from "@/types/contest";

export const mockContests: Contest[] = [
  {
    id: "contest-openai-safety-sprint",
    slug: "openai-safety-sprint",
    title: "OpenAI Safety Sprint",
    organizer: "OpenAI Builders",
    shortDescription: "Production-grade LLM safety evaluation workflow를 설계하는 글로벌 해커톤.",
    description:
      "Teams build a safety or evaluation workflow for LLM applications. The winning entries combine measurable guardrails, strong user value, and a polished product demo.",
    url: "https://example.com/openai-safety-sprint",
    sourceUrl: "https://example.com/openai-safety-sprint/brief",
    startDate: "2026-03-01",
    deadline: "2026-03-14",
    eventDate: "2026-03-28",
    participationMode: "hybrid",
    location: "San Francisco / Online",
    eligibilityText: "Global applicants welcome. Student, startup, and indie teams can apply.",
    eligibilitySegments: ["global", "student", "startup", "developer"],
    difficulty: "advanced",
    teamAllowed: true,
    minTeamSize: 1,
    maxTeamSize: 4,
    language: "English",
    globalParticipation: true,
    prizePoolKrw: 72500000,
    prizeSummary: "총상금 약 7,250만원 + 멘토 오피스 아워",
    submissionFormat: "Working demo, GitHub repo, 5 minute walkthrough video",
    toolsAllowed: ["OpenAI API", "TypeScript", "Python"],
    datasetProvided: false,
    datasetSummary: "Teams define their own benchmark or evaluation dataset.",
    aiCategories: ["llm-agents", "ai-infra-systems"],
    tags: ["Agent", "Safety", "Evaluation", "RAG"],
    badges: ["deadline_urgent", "high_prize", "global", "trending_ai", "developer_friendly"],
    status: "published",
    analysis: {
      summary:
        "LLM 서비스의 안전성, 평가 체계, 제품 데모 완성도를 동시에 보여줘야 하는 상위권 지향 대회입니다.",
      recommendReason:
        "Agent, eval, guardrail 경험을 포트폴리오로 남기기 좋고, 단순 아이디어보다 구현과 측정 설계가 강하게 평가됩니다.",
      winStrategy:
        "1. 단일 데모보다 반복 가능한 evaluation loop를 먼저 설계합니다.\n2. 실패 사례와 개선 지표를 같이 제시해 신뢰도를 확보합니다.\n3. 실사용 시나리오 한 가지를 깊게 파서 데모 완성도를 높입니다.",
      difficultyAnalysis:
        "Advanced. 제품 UX, 평가 설계, 프롬프트 안전성까지 같이 다뤄야 해서 단순 API 연결 수준을 넘어섭니다.",
      judgingFocus: "Reliable evaluation, concrete safety metrics, polished user demo",
      promptVersion: "contest-v1",
      modelName: "gpt-4.1",
      analysisStatus: "completed",
    },
  },
  {
    id: "contest-campus-rag-league",
    slug: "campus-rag-league",
    title: "Campus RAG League",
    organizer: "Korea AI Student Network",
    shortDescription: "학생 팀이 빠르게 RAG 기반 MVP를 만들 수 있도록 설계된 대학생 중심 리그.",
    description:
      "Build an AI assistant that helps students navigate campus life. Teams are judged on usefulness, retrieval quality, and demo clarity rather than custom model training.",
    url: "https://example.com/campus-rag-league",
    sourceUrl: "https://example.com/campus-rag-league/faq",
    startDate: "2026-03-08",
    deadline: "2026-03-21",
    eventDate: "2026-03-30",
    participationMode: "online",
    location: "Online",
    eligibilityText: "Open to university students and recent graduates.",
    eligibilitySegments: ["student", "education"],
    difficulty: "beginner",
    teamAllowed: true,
    minTeamSize: 1,
    maxTeamSize: 5,
    language: "Korean",
    globalParticipation: false,
    prizePoolKrw: 8700000,
    prizeSummary: "총상금 약 870만원 + 캠퍼스 쇼케이스",
    submissionFormat: "Live demo, slide deck, deployment link",
    toolsAllowed: ["Any LLM API", "Supabase", "Next.js"],
    datasetProvided: true,
    datasetSummary: "Starter campus knowledge base and FAQ export included.",
    aiCategories: ["llm-agents", "ai-for-social-good"],
    tags: ["RAG", "Education", "Campus", "Student"],
    badges: ["student_friendly", "developer_friendly", "beginner_friendly"],
    status: "published",
    analysis: {
      summary:
        "모델 학습보다 문제정의와 검색 품질이 중요해서 학생 개발팀이 MVP 감각을 빠르게 키우기 좋은 대회입니다.",
      recommendReason:
        "Supabase와 LLM API만으로도 경쟁력 있는 결과물을 만들 수 있고, 실제 사용자 문제를 풀면 차별화가 쉽습니다.",
      winStrategy:
        "1. 학사 일정, 장학금, 수강신청처럼 반복 질문이 많은 문제를 고릅니다.\n2. 검색 실패 케이스를 먼저 모아 RAG 품질을 안정화합니다.\n3. 학생 인터뷰나 사용 로그를 데모에 포함해 실효성을 증명합니다.",
      difficultyAnalysis:
        "Beginner. 파인튜닝 없이도 완성 가능한 구조지만, 정보 구조화와 답변 신뢰도는 꼼꼼히 챙겨야 합니다.",
      judgingFocus: "Student utility, retrieval accuracy, demo clarity",
      promptVersion: "contest-v1",
      modelName: "gpt-4.1-mini",
      analysisStatus: "completed",
    },
  },
  {
    id: "contest-vision-for-climate",
    slug: "vision-for-climate",
    title: "Vision for Climate Challenge",
    organizer: "Earth Compute Lab",
    shortDescription: "위성 이미지와 현장 데이터를 활용해 기후 리스크를 감지하는 CV 중심 챌린지.",
    description:
      "Participants identify climate-related risks from multimodal environmental data. Strong submissions combine detection accuracy with decision-ready reporting.",
    url: "https://example.com/vision-for-climate",
    sourceUrl: "https://example.com/vision-for-climate/rules",
    startDate: "2026-03-15",
    deadline: "2026-04-05",
    eventDate: "2026-04-20",
    participationMode: "online",
    location: "Online",
    eligibilityText: "Open internationally to researchers, startups, and students.",
    eligibilitySegments: ["global", "research", "student"],
    difficulty: "advanced",
    teamAllowed: true,
    minTeamSize: 1,
    maxTeamSize: 4,
    language: "English",
    globalParticipation: true,
    prizePoolKrw: 36250000,
    prizeSummary: "총상금 약 3,625만원 + 클라우드 크레딧",
    submissionFormat: "Technical report, code, inference notebook, short demo",
    toolsAllowed: ["PyTorch", "TensorFlow", "Any open dataset tooling"],
    datasetProvided: true,
    datasetSummary: "Satellite imagery and historical labels are provided.",
    aiCategories: ["computer-vision", "ai-for-social-good"],
    tags: ["Satellite", "Detection", "Climate", "Monitoring"],
    badges: ["high_prize", "global"],
    status: "published",
    analysis: {
      summary:
        "정확도뿐 아니라 실제 의사결정에 쓸 수 있는 리포팅 방식까지 요구하는, 연구 성격이 강한 비전 대회입니다.",
      recommendReason:
        "CV 포트폴리오에 사회적 임팩트를 더할 수 있고, 명확한 데이터셋이 제공되어 실험 설계를 깊게 가져가기 좋습니다.",
      winStrategy:
        "1. 데이터 편향과 계절성 문제를 먼저 분석합니다.\n2. 성능 숫자만이 아니라 현장 해석이 가능한 리포트 형식을 제안합니다.\n3. 실패 케이스 시각화를 통해 모델 한계를 투명하게 보여줍니다.",
      difficultyAnalysis:
        "Advanced. 베이스라인을 넘는 것도 중요하지만, 도메인 해석력과 결과 전달 방식이 같이 평가됩니다.",
      judgingFocus: "Detection quality, robustness, decision-ready reporting",
      promptVersion: "contest-v1",
      modelName: "gpt-4.1",
      analysisStatus: "completed",
    },
  },
  {
    id: "contest-multimodal-studio-jam",
    slug: "multimodal-studio-jam",
    title: "Multimodal Studio Jam",
    organizer: "Creator Tools Collective",
    shortDescription: "텍스트, 이미지, 음성을 함께 엮어 제작 경험을 재구성하는 멀티모달 제작 해커톤.",
    description:
      "Build a creative workflow that blends image, speech, and language models. Judges are looking for product taste, smooth interaction design, and believable creator value.",
    url: "https://example.com/multimodal-studio-jam",
    sourceUrl: "https://example.com/multimodal-studio-jam/overview",
    startDate: "2026-03-04",
    deadline: "2026-03-16",
    eventDate: "2026-03-24",
    participationMode: "hybrid",
    location: "Seoul / Online",
    eligibilityText: "Open to designers, developers, and creator teams.",
    eligibilitySegments: ["creator", "developer", "designer"],
    difficulty: "intermediate",
    teamAllowed: true,
    minTeamSize: 1,
    maxTeamSize: 3,
    language: "English",
    globalParticipation: true,
    prizePoolKrw: 21750000,
    prizeSummary: "총상금 약 2,175만원 + 데모데이 참가",
    submissionFormat: "Interactive prototype, prompt sheet, product walkthrough",
    toolsAllowed: ["OpenAI API", "Replicate", "Figma", "Next.js"],
    datasetProvided: false,
    datasetSummary: "No fixed dataset. Teams are expected to define their own creator workflow.",
    aiCategories: ["multimodal-ai", "generative-ai"],
    tags: ["Multimodal", "Creative", "Speech", "Image"],
    badges: ["deadline_urgent", "high_prize", "global", "trending_ai", "developer_friendly"],
    status: "published",
    analysis: {
      summary:
        "제품 감도와 AI 활용 구조를 동시에 보여줘야 해서, 디자인과 구현 균형이 중요한 멀티모달 해커톤입니다.",
      recommendReason:
        "창작 툴, 에이전트 워크플로, 이미지 생성 경험을 하나로 묶는 포트폴리오를 만들기에 적합합니다.",
      winStrategy:
        "1. 기능을 넓히기보다 창작자 한 페르소나를 좁게 잡습니다.\n2. 입력과 출력 사이의 흐름을 영상으로 보여줄 수 있게 설계합니다.\n3. 사람이 수정하는 지점을 명확히 드러내 협업형 AI라는 메시지를 만듭니다.",
      difficultyAnalysis:
        "Intermediate. 모델 자체보다 경험 설계가 중요하고, 시연 품질이 순위에 큰 영향을 줍니다.",
      judgingFocus: "Product taste, creator workflow fit, demo smoothness",
      promptVersion: "contest-v1",
      modelName: "gpt-4.1-mini",
      analysisStatus: "completed",
    },
  },
  {
    id: "contest-healthcare-ai-signal-cup",
    slug: "healthcare-ai-signal-cup",
    title: "Healthcare AI Signal Cup",
    organizer: "MediSignal Foundation",
    shortDescription: "의료 시계열과 환자 리스크 예측 문제를 다루는 데이터 사이언스 경쟁형 챌린지.",
    description:
      "Teams predict critical care risk signals from structured hospital data. The competition values calibration, explainability, and clinically useful prioritization.",
    url: "https://example.com/healthcare-ai-signal-cup",
    sourceUrl: "https://example.com/healthcare-ai-signal-cup/data",
    startDate: "2026-03-18",
    deadline: "2026-04-12",
    eventDate: "2026-04-26",
    participationMode: "online",
    location: "Online",
    eligibilityText: "Open worldwide. Healthcare experience is helpful but not required.",
    eligibilitySegments: ["global", "research", "healthcare"],
    difficulty: "advanced",
    teamAllowed: true,
    minTeamSize: 1,
    maxTeamSize: 4,
    language: "English",
    globalParticipation: true,
    prizePoolKrw: 43500000,
    prizeSummary: "총상금 약 4,350만원 + publication support",
    submissionFormat: "Prediction file, technical report, model card",
    toolsAllowed: ["Python", "XGBoost", "PyTorch"],
    datasetProvided: true,
    datasetSummary: "Structured patient monitoring dataset with evaluation server.",
    aiCategories: ["data-science", "ai-for-social-good"],
    tags: ["Healthcare", "Time Series", "Risk", "Calibration"],
    badges: ["high_prize", "global"],
    status: "published",
    analysis: {
      summary:
        "리더보드 싸움에 그치지 않고 calibration과 설명 가능성을 같이 요구하는 의료 데이터 대회입니다.",
      recommendReason:
        "실험 설계, 피처 엔지니어링, 모델 검증 능력을 한 번에 보여줄 수 있어 데이터 사이언스 포트폴리오 가치가 높습니다.",
      winStrategy:
        "1. 단순 AUC보다 calibration 개선 전략을 초기에 포함합니다.\n2. leakage 가능성을 점검하고 시계열 split을 엄격히 유지합니다.\n3. 임상적으로 해석 가능한 feature narrative를 함께 제시합니다.",
      difficultyAnalysis:
        "Advanced. 모델링 난도도 높지만 평가 방식과 도메인 해석을 같이 맞춰야 경쟁력이 생깁니다.",
      judgingFocus: "Calibration, ranking quality, explainability",
      promptVersion: "contest-v1",
      modelName: "gpt-4.1",
      analysisStatus: "completed",
    },
  },
  {
    id: "contest-roboops-field-test",
    slug: "roboops-field-test",
    title: "RoboOps Field Test",
    organizer: "Autonomy Works",
    shortDescription: "현장 작업 로봇의 작업 계획과 복구 시나리오를 검증하는 로보틱스 운영 챌린지.",
    description:
      "Build an autonomy workflow that plans, recovers, and reports clearly in dynamic field environments. Judges reward reliability and operational clarity over flashy demos.",
    url: "https://example.com/roboops-field-test",
    sourceUrl: "https://example.com/roboops-field-test/spec",
    startDate: "2026-03-10",
    deadline: "2026-03-25",
    eventDate: "2026-04-02",
    participationMode: "offline",
    location: "Daejeon",
    eligibilityText: "Open to robotics teams and embedded developers in Korea.",
    eligibilitySegments: ["robotics", "developer", "embedded"],
    difficulty: "advanced",
    teamAllowed: true,
    minTeamSize: 2,
    maxTeamSize: 5,
    language: "Korean",
    globalParticipation: false,
    prizePoolKrw: 17400000,
    prizeSummary: "총상금 약 1,740만원 + 하드웨어 스폰서 크레딧",
    submissionFormat: "On-site demo, system architecture sheet, failure log",
    toolsAllowed: ["ROS", "Python", "C++"],
    datasetProvided: false,
    datasetSummary: "Teams bring their own planning stack and logging setup.",
    aiCategories: ["robotics", "ai-infra-systems"],
    tags: ["Robotics", "Planning", "Recovery", "Operations"],
    badges: ["high_prize", "developer_friendly"],
    status: "published",
    analysis: {
      summary:
        "화려한 생성형 데모보다 안정적인 계획 수립과 복구 루틴이 중요한 실전형 로보틱스 대회입니다.",
      recommendReason:
        "로보틱스 팀이 흔히 놓치는 운영 가시성과 실패 로그 설계를 차별화 포인트로 가져갈 수 있습니다.",
      winStrategy:
        "1. 정상 경로보다 recovery path를 먼저 설계합니다.\n2. 작업 상태와 실패 원인을 운영자가 바로 이해할 수 있게 시각화합니다.\n3. 현장 데모 리스크를 줄이는 작은 범위의 안정적 시나리오를 택합니다.",
      difficultyAnalysis:
        "Advanced. 현장 환경의 변수를 다뤄야 하고, 시스템 안정성이 점수 대부분을 좌우합니다.",
      judgingFocus: "Operational reliability, recovery flow, demo stability",
      promptVersion: "contest-v1",
      modelName: "gpt-4.1-mini",
      analysisStatus: "completed",
    },
  },
];
